name: todo_list
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  sqflite: ^2.0.3+1
  path: ^1.8.1
  google_fonts: ^3.0.1
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^5.4.2
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  asuka: ^2.0.1+3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
